name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths: [ "backend/**" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: cicd-demo-backend
  ECS_CLUSTER: cicd-demo-cluster
  ECS_SERVICE: cicd-demo-task-service-ryns0yn1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Image (with unique tag)
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker build --no-cache -t $IMAGE_URI ./backend
          docker push $IMAGE_URI

          echo "Built and pushed: $IMAGE_URI"

      - name: Register new ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition cicd-demo-task \
            --query 'taskDefinition' > task-def.json

          cat task-def.json | jq --arg IMAGE "$IMAGE_URI" '
            .containerDefinitions[0].image = $IMAGE
            | {
                family: .family,
                networkMode: .networkMode,
                containerDefinitions: .containerDefinitions,
                requiresCompatibilities: .requiresCompatibilities,
                cpu: .cpu,
                memory: .memory,
                executionRoleArn: .executionRoleArn
              }
          ' > new-task-def.json

          echo "Registering task definition..."
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: Update ECS service to new task
        run: |
          NEW_TASK_DEF=$(aws ecs list-task-definitions \
            --family-prefix cicd-demo-task \
            --sort DESC \
            --max-items 1 \
            --query "taskDefinitionArns[0]" \
            --output text)

          echo "Using task definition: $NEW_TASK_DEF"

          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition "$NEW_TASK_DEF" \
            --force-new-deployment

          echo "Deployment triggered."