name: Backend CI/CD
on:
  push:
    branches: [ main ]
    paths: [ "backend/**" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: cicd-demo-backend
  ECS_CLUSTER: cicd-demo-cluster
  ECS_SERVICE: cicd-demo-task-service-ryns0yn1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://nexcod.narad.io   # optional
      
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}    # ðŸ‘ˆ unique tag for every commit
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} backend/
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
      - name: Register new ECS task definition revision
        run: |
          aws ecs describe-task-definition --task-definition cicd-demo-task \
          --query 'taskDefinition' > task-def.json
          cat task-def.json | jq --arg IMAGE "$IMAGE_URI" '
          .containerDefinitions[0].image = $IMAGE
          | {
              family: .family,
              networkMode: .networkMode,
              containerDefinitions: .containerDefinitions,
              requiresCompatibilities: .requiresCompatibilities,
              cpu: .cpu,
              memory: .memory,
              executionRoleArn: .executionRoleArn
            }
          ' > new-task-def.json
          echo "âœ… Clean new task definition generated:"
          cat new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --force-new-deployment
